# #1 How do you install Pytorch?

In [2]:
# To install PyTorch, run the following command in your terminal or command prompt:
# Note: Make sure you have Python and pip already installed on your system.

!pip install torch torchvision torchaudio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 586.5 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 590.8 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 591.3 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 445.1 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 587.8 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 589.5 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 588.7 kB/s eta 0:00:0000:0100:01


# #2 How do you create a tensor in Pytorch?

In [16]:
import torch

# Create a tensor of size 2x3 filled with zeros
tensor1 = torch.zeros(3, 3)
tensor2 = torch.ones(3, 3)
print(tensor1, "\n", tensor2)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


# 3. How do you perform matrix operations between two tensors?

In [20]:
import torch

# Create two tensors
tensor1 = torch.rand(2, 3)  # Random tensor of size 2x3
tensor2 = torch.rand(3, 4)  # Random tensor of size 3x4

Matrix multiplication result:
 tensor([[0.5480, 0.9859, 0.6883, 1.2514],
        [0.8673, 1.4120, 1.0859, 1.2053]])
Element-wise multiplication result:
 tensor([[0.0807, 0.3508],
        [0.6726, 0.6393]])
Matrix addition result:
 tensor([[0.5869, 1.3129, 1.9676],
        [1.3626, 0.9158, 1.1420]])
Matrix subtraction result:
 tensor([[ 0.0599, -0.3059,  0.0175],
        [ 0.2590,  0.6141,  0.0719]])
Dot product result:
 tensor(32)
Batch matrix multiplication result:
 tensor([[[0.7888, 0.7791, 1.0238, 0.9735],
         [1.0529, 0.3874, 1.2175, 1.1655]],

        [[0.9051, 1.1730, 0.7145, 0.7950],
         [1.2896, 1.6108, 0.9312, 0.9949]],

        [[2.1174, 0.4315, 1.4166, 0.8035],
         [0.7895, 0.0943, 0.6461, 0.3758]],

        [[0.1659, 0.7418, 1.0728, 1.3686],
         [0.1508, 0.5837, 0.7477, 0.8996]],

        [[0.8932, 0.8423, 0.6900, 0.9548],
         [1.0336, 0.9057, 0.7965, 1.0265]],

        [[0.7020, 0.3873, 0.5396, 0.2477],
         [1.2412, 0.9351, 0.6935, 0.8813]],



In [ ]:
# Matrix multiplication
result_mm = torch.mm(tensor1, tensor2)
print("Matrix multiplication result:\n", result_mm)

In [ ]:
# Element-wise multiplication
result_mul = tensor1[:, :2] * tensor2[:2, :2]  # Shapes must match
print("Element-wise multiplication result:\n", result_mul)

In [ ]:
# Matrix addition
tensor3 = torch.rand(2, 3)  # Tensor of size 2x3
result_add = tensor1 + tensor3
print("Matrix addition result:\n", result_add)

In [ ]:
# Matrix subtraction
result_sub = tensor1 - tensor3
print("Matrix subtraction result:\n", result_sub)

In [ ]:
# Dot product (for 1-D tensors)
vec1 = torch.tensor([1, 2, 3])
vec2 = torch.tensor([4, 5, 6])
result_dot = torch.dot(vec1, vec2)
print("Dot product result:\n", result_dot)

In [ ]:
# Batch matrix multiplication
tensor4 = torch.rand(10, 2, 3)  # Random batch of matrices of size 2x3
tensor5 = torch.rand(10, 3, 4)  # Random batch of matrices of size 3x4
result_bmm = torch.bmm(tensor4, tensor5)
print("Batch matrix multiplication result:\n", result_bmm)

# 4. How do you compute the gradient of a function in PyTorch?

In [21]:
# create tensor and set requires_grad

x = torch.tensor([2.0], requires_grad=True)

# define function
y = x ** 2

y.backward()

print(x.grad)

tensor([4.])


# 5. How do you use a GPU for tensor computations in PyTorch?

In [22]:
import torch

# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    device = torch.device("cuda")  # Use GPU
    x = torch.tensor([1.0, 2.0]).to(device)  # Create a tensor and move it to GPU
    print(x)
else:
    print("CUDA is not available. Running on CPU.")


CUDA is not available. Running on CPU.


#  6. How do you define a neural network model in PyTorch?

# 7. How do you train a model in PyTorch?

# 8. Example - MNIST

In [46]:
!pip install ipywidgets
!pip install --upgrade jupyterlab ipywidgets
!jupyter nbextension enable --py widgetsnbextension --sys-prefix

2648.49s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
from IPython.display import display
import ipywidgets as widgets
from ipywidgets import interact, interact_manual

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


In [3]:
def load_data(batch_size=32):
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])

    train_dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    test_dataset = datasets.MNIST('./data', train=False, transform=transform)
    test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
    
    return train_loader, test_loader


In [4]:
def train(model, device, train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        data = data.view(-1, 28 * 28)
        optimizer.zero_grad()
        output = model(data)
        loss = F.cross_entropy(output, target)
        loss.backward()
        optimizer.step()

In [7]:
@interact_manual
def train_and_visualize(learning_rate=(0.001, 0.1, 0.001), epochs=(1, 10), batch_size=[32, 64, 128, 256]):
    train_loader, test_loader = load_data(batch_size)
    model = Net()
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.5)
    for epoch in range(1, epochs + 1):
        train(model, "cpu", train_loader, optimizer, epoch)
    
    # Visualization and performance statistics
    correct_predictions = 0
    total_predictions = 0
    examples = enumerate(test_loader)
    batch_idx, (example_data, example_targets) = next(examples)
    
    with torch.no_grad():
        output = model(example_data.view(-1, 28 * 28))
        # Get the index of the max log-probability (the predicted label)
        pred = output.argmax(dim=1, keepdim=True)
        correct_predictions += pred.eq(example_targets.view_as(pred)).sum().item()
        total_predictions += example_data.shape[0]

    # Calculate accuracy
    accuracy = correct_predictions / total_predictions * 100
    
    # Adjust the figure size if necessary
    fig = plt.figure(figsize=(15, 8))  # Adjusted for better display of 12 images
    # Loop to display 12 examples
    for i in range(12):
        plt.subplot(3, 4, i+1)  # Adjusted for a 3x4 grid
        plt.tight_layout()
        plt.imshow(example_data[i][0], cmap='gray', interpolation='none')
        plt.title("Prediction: {} (True: {})".format(pred[i].item(), example_targets[i]))
        plt.xticks([])
        plt.yticks([])
    
    plt.show()
    print(f"Accuracy: {accuracy:.2f}%")

interactive(children=(FloatSlider(value=0.05, description='learning_rate', max=0.1, min=0.001, step=0.001), In…